### ISSUE TITLE
pa.ABE text in the picture is cut off

### ISSUE THREAD

**Issue by certara-mtomashevskiy** [Detlew/PowerTOST#4]
try 
pa.ABE(CV=0.29, targetpower = 0.9, minpower = 0.8)
screen(4) does show the info in the 4th screen,but it is partially cutted and unusable
Checked in R 3.6.0

**Comment by certara-mtomashevskiy** [comment]
![Rplot](https://user-images.githubusercontent.com/39342614/62573768-77c1a100-b89f-11e9-81f1-9e31161d1db4.jpeg)

**Comment by Helmut01** [comment]
Your screenhot looks like the graphics window of RStudio which is notorious for its awful rendering. This is what I get in the native R 3.6.1 graphics device on Windows:

![test](https://user-images.githubusercontent.com/19939535/62579478-2bc52b00-b8a4-11e9-84f9-3cedfaf1fbbe.png)
This is what I get in RStudio 1.1.463 with my usual window sizes:

![test2](https://user-images.githubusercontent.com/19939535/62579702-c02f8d80-b8a4-11e9-91cd-c99b492fedc4.png)
I could reproduce yours with an extreme aspect ratio. I tried to force a square plotting region in the source of pwrA_S3methods.R by setting `par(pty = "s")`.
Still OK in the graphics device but even worse in RStudio:

![test3](https://user-images.githubusercontent.com/19939535/62580445-6cbe3f00-b8a6-11e9-9509-44ab347dec24.png)
Hence, that’s an issue of RStudio and not the package. Theoretically (!) it should be possible to obtain the current window size from the depths of RStudio and recalculate/adjust _all_ graphics parameters in user coordinates. That’s beyond me. I can only suggest to the RGui instead.
