### ISSUE TITLE
More precize points for Gauss quadrature for tfn function

### ISSUE THREAD

**Issue by PharmCat** [Detlew/PowerTOST#6]
Maybe it will be usefull

   r   <- c(0.14776211235737646, 0.13463335965499826, 0.10954318125799103, 0.07472567457529028, 0.033335672154344104)
   u   <- c(0.07443716949081561, 0.2166976970646236, 0.3397047841495122, 0.43253168334449227, 0.48695326425858587)

**Comment by Detlew** [comment]
Dear Pharmcat,
do you have a reference for these values?
If yes I will insert them into my code. Thank you.

**Comment by PharmCat** [comment]
Hi!

As described in the article https://www.jstor.org/stable/2347148 10 points Gauss quadrature was taken and halved, 5 upper points used for this algorithm.  Julia package FastGaussQuadrature was used to calculate 10 points:

```julia
using FastGaussQuadrature
(gausslegendre(10)[1]/2)[6:end]
(gausslegendre(10)[2]/2)[6:end]
```
https://juliaapproximation.github.io/FastGaussQuadrature.jl/dev/gaussquadrature/#Gauss-Legendre-quadrature

Also,  values were checked with the table here:
https://pomax.github.io/bezierinfo/legendre-gauss.html#n10

And here:
https://amath.colorado.edu/faculty/martinss/Nystrom/Gaussian_quadrature.pdf

**Comment by Detlew** [comment]
Coefficients introduced in code.
